import { constructMetadata } from '@/lib/metadata';
import {
  TopicClusterPage,
  type ClusterPageContent,
} from '@/components/seo/topic-cluster-page';
import type { Metadata } from 'next';

export const metadata: Metadata = constructMetadata({
  title: 'Text-to-Lip-Sync Video Examples & AI Voice Showcase',
  description:
    'Explore real-world text-to-lip-sync video samples. Showcase of multilingual AI voiceovers, e-learning avatars, and commercial promo videos.',
  pathname: '/text-to-lip-sync/examples',
});

const content: ClusterPageContent = {
  title: 'Text to Lip Sync Examples & Voice Samples',
  badge: 'Examples & Demos',
  description:
    'Browse video examples generated from plain text scripts. Discover how different AI voice temperaments and language accents look when combined with audio-driven facial animation.',
  pillarTitle: 'Text to Lip Sync',
  pillarRoute: '/text-to-lip-sync',
  sections: [
    {
      heading: '1. Commercial Product Demonstrations',
      subheading: 'Marketing Voiceovers',
      content: [
        'E-commerce ad clips generated by typing product features into the text editor, paired with an energetic female voice actor.',
      ],
    },
    {
      heading: '2. Multilingual E-Learning Tutorials',
      subheading: 'Educational Content',
      content: [
        'Instructional videos translated from English to French and Japanese using text-driven voice synthesis and lip alignment.',
      ],
    },
  ],
  lsiKeywords: [
    'Text to lip sync examples',
    'AI voice video demos',
    'Script to video sample gallery',
  ],
  faqs: [
    {
      question: 'Can I clone my own voice for text-to-lip-sync?',
      answer:
        'Voice cloning integration is coming soon to our Enterprise tier.',
    },
  ],
};

export default function ExamplesTextToLipSyncPage() {
  return <TopicClusterPage content={content} />;
}
